blank_issues_enabled: true
contact_links:
  - name: Feedback ğŸ‘
    url: https://github.com/jpmorganchase/uitk/discussions/categories/feedback
    about: To provide feedback on any aspect of the Salt design system please create a new discussion in our forum's feedback section
