blank_issues_enabled: true
contact_links:
  - name: Feedback ğŸ‘
    url: https://github.com/jpmorganchase/uitk/discussions/categories/feedback
    about: Provide feedback on any aspect of the design system by creating a new discussion in our forum.
